// ═══════════════════════════════════════════════════════════════
// CODE EXECUTION — Content Data
// This file is auto-generated by scripts/update_content.py
// To update the page, run the script or trigger the GitHub Action
// ═══════════════════════════════════════════════════════════════

const SITE_DATA = {
  lastUpdated: "2026-06-21",
  models: [
    {
      tag: "Anthropic",
      tagClass: "",
      date: "Anthropic · May 28, 2026",
      title: "Claude Opus 4.8",
      description: "Anthropic's most capable model — upgraded with stronger coding, agentic task performance, and professional work. Designed for long-running autonomous tasks with improved consistency.",
      sourceUrl: "https://www.anthropic.com/news/claude-opus-4-8",
      sourceLabel: "anthropic.com",
      svgLabel1: "CLAUDE_OPUS_4.8",
      svgLabel2: "ANTHROPIC",
      svgTitle: "OPUS 4.8",
      svgDate: "MAY 2026",
      svgSub: "CODING · AGENTIC · REASONING"
    },
    {
      tag: "Anthropic",
      tagClass: "",
      date: "Anthropic · Jun 9, 2026",
      title: "Claude Fable 5 & Mythos 5",
      description: "Dual model release. Fable 5 and Mythos 5 are Anthropic's latest tier models. Subsequently subject to US government export control directive suspending access.",
      sourceUrl: "https://www.anthropic.com/news/claude-fable-5-mythos-5",
      sourceLabel: "anthropic.com",
      svgLabel1: "DUAL_MODEL_RELEASE",
      svgTitle: "FABLE 5",
      svgTitle2: "MYTHOS 5",
      svgDate: "JUN 2026 · RESTRICTED ACCESS",
      svgSub: "EXPORT CONTROL SUBJECT"
    },
    {
      tag: "Google",
      tagClass: "",
      date: "Google DeepMind · Jun 2026",
      title: "Gemini Omni & Gemini 3.5",
      description: "Google DeepMind's latest models with native multimodal capabilities across text, image, audio, and video. Gemini Omni brings unified perception, while 3.5 pushes reasoning boundaries.",
      sourceUrl: "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-omni-3-5-videos/",
      sourceLabel: "blog.google",
      svgLabel1: "GOOGLE_DEEPMIND",
      svgTitle: "GEMINI OMNI",
      svgTitle2: "+ GEMINI 3.5",
      svgDate: "MULTIMODAL · 2026",
      svgSub: "TEXT · IMAGE · AUDIO · VIDEO"
    },
    {
      tag: "DeepSeek",
      tagClass: "amber",
      date: "DeepSeek · Jun 2026",
      title: "DeepSeek V4 (Preview)",
      description: "Preview release of DeepSeek V4 with world-top-tier reasoning performance and significantly upgraded agent capabilities. Available on web, app, and API. Continues the open-source tradition.",
      sourceUrl: "https://www.deepseek.com",
      sourceLabel: "deepseek.com",
      svgLabel1: "DEEPSEEK_PREVIEW",
      svgTitle: "V4 PREVIEW",
      svgDate: "WORLD-CLASS REASONING",
      svgSub: "OPEN-SOURCE · MIT LICENSE"
    },
    {
      tag: "Trend",
      tagClass: "",
      date: "Industry Trend · 2026",
      title: "Reasoning Models Go Mainstream",
      description: "Extended thinking and chain-of-thought reasoning are now standard across all major providers — Anthropic, Google, OpenAI, DeepSeek. Models \"think\" before responding, enabling complex multi-step problem solving.",
      sourceUrl: "https://www.anthropic.com/news/claude-opus-4-8",
      sourceLabel: "anthropic.com",
      svgLabel1: "REASONING_MODELS",
      svgTitle: "EXTENDED THINKING",
      svgDate: "2026 MAINSTREAM",
      svgSub: "CHAIN-OF-THOUGHT · AGENTS"
    }
  ],
  applications: [
    {
      tag: "Google",
      tagClass: "",
      date: "Google · Jun 2026",
      title: "Gemini for Science",
      description: "A new collection of science tools and experiments built on Gemini to expand the scale and precision of scientific exploration. AI-powered experiments for researchers.",
      sourceUrl: "https://blog.google/innovation-and-ai/technology/research/gemini-for-science-io-2026/",
      sourceLabel: "blog.google",
      svgLabel1: "GOOGLE_RESEARCH",
      svgTitle: "GEMINI FOR",
      svgTitle2: "SCIENCE",
      svgDate: "IO 2026 · NEW ERA OF DISCOVERY"
    },
    {
      tag: "Google",
      tagClass: "",
      date: "Google Research · Jun 2026",
      title: "AMIE — Medical AI",
      description: "New research published in Nature shows how AMIE, Google's medical AI, could help manage health conditions. A diagnostic and management conversation agent for clinical use.",
      sourceUrl: "https://blog.google/innovation-and-ai/models-and-research/google-research/amie-for-disease-management-in-nature/",
      sourceLabel: "blog.google",
      svgLabel1: "GOOGLE_RESEARCH · NATURE",
      svgTitle: "AMIE",
      svgDate: "DISEASE MANAGEMENT",
      svgSub: "PUBLISHED IN NATURE"
    },
    {
      tag: "Anthropic",
      tagClass: "",
      date: "Anthropic · 2026",
      title: "Claude Code",
      description: "CLI-based AI coding agent that navigates codebases, edits files, runs commands, and manages git operations autonomously. Now powered by Claude Opus 4.8 for extended coding sessions.",
      sourceUrl: "https://www.anthropic.com/news/claude-opus-4-8",
      sourceLabel: "anthropic.com",
      svgLabel1: "CLI_CODING_AGENT",
      svgTitle: "CLAUDE CODE",
      svgDate: "POWERED BY OPUS 4.8",
      svgSub: "CODEBASE · GIT · PR REVIEW"
    },
    {
      tag: "DeepMind",
      tagClass: "",
      date: "Google DeepMind · Jun 2026",
      title: "Project Genie + Street View",
      description: "DeepMind's Project Genie expands to simulate real-world places using Street View data. Creates interactive, navigable environments from geographic data — a step toward world-model AI.",
      sourceUrl: "https://blog.google/innovation-and-ai/models-and-research/google-deepmind/project-genie-expands/",
      sourceLabel: "blog.google",
      svgLabel1: "GOOGLE_DEEPMIND",
      svgTitle: "PROJECT GENIE",
      svgDate: "SIMULATE REAL-WORLD PLACES",
      svgSub: "INTERACTIVE ENVIRONMENTS"
    },
    {
      tag: "DeepMind",
      tagClass: "",
      date: "Google DeepMind · Jun 2026",
      title: "Running Guide Agent",
      description: "A step towards running unbounded — DeepMind's research into agents that can operate autonomously over extended periods without human intervention. Tackles the \"unbounded execution\" problem.",
      sourceUrl: "https://blog.google/innovation-and-ai/models-and-research/google-deepmind/running-guide-agent/",
      sourceLabel: "blog.google",
      svgLabel1: "DEEPMIND_RESEARCH",
      svgTitle: "RUNNING GUIDE",
      svgDate: "RUNNING UNBOUNDED",
      svgSub: "EXTENDED-HORIZON TASKS"
    },
    {
      tag: "Google",
      tagClass: "",
      date: "Google · Jun 2026",
      title: "AI Content Provenance",
      description: "Google makes it easier to understand how content was created and edited — new tools for identifying AI-generated media online through provenance signals and metadata labels.",
      sourceUrl: "https://blog.google/innovation-and-ai/products/identifying-ai-generated-media-online/",
      sourceLabel: "blog.google",
      svgLabel1: "AI_TRANSPARENCY",
      svgTitle: "CONTENT PROVENANCE",
      svgDate: "IDENTIFY AI-GENERATED MEDIA",
      svgSub: "SIGNALS · LABELS · METADATA"
    }
  ],
  articles: [
    {
      source: "MIT Technology Review",
      date: "Jun 19, 2026",
      title: "A startup claims it broke through a bottleneck that's holding back LLMs",
      description: "Subquadratic has shared details about its new model architecture. Some remain skeptical, but the approach could address scaling limitations.",
      url: "https://www.technologyreview.com/2026/06/19/1139313/a-startup-claims-it-broke-through-a-bottleneck-thats-holding-back-llms/",
      sourceLabel: "techreview.com"
    },
    {
      source: "MIT Technology Review",
      date: "Jun 11, 2026",
      title: "Google DeepMind is worried about what happens when millions of agents start to interact",
      description: "The firm is calling for more scientists to study the risks of multi-agent systems and emergent behaviors.",
      url: "https://www.technologyreview.com/2026/06/11/1138794/google-deepmind-is-worried-about-what-happens-when-millions-of-agents-start-to-interact/",
      sourceLabel: "techreview.com"
    },
    {
      source: "MIT Technology Review",
      date: "Jun 9, 2026",
      title: "Five things you need to know about AI",
      description: "At SXSW London, MIT Tech Review's senior editor laid out how he's thinking about AI in 2026 — covering agents, reasoning, safety, and scale.",
      url: "https://www.technologyreview.com/2026/06/09/1138582/five-things-you-need-to-know-about-ai/",
      sourceLabel: "techreview.com"
    },
    {
      source: "MIT Technology Review",
      date: "Jun 5, 2026",
      title: "The Meta hack shows there's more to AI security than Mythos",
      description: "Some AI cybersecurity threats are incredibly simple. They're still dangerous — and not all risks require frontier-level capabilities.",
      url: "https://www.technologyreview.com/2026/06/05/1138437/the-meta-hack-shows-theres-more-to-ai-security-than-mythos/",
      sourceLabel: "techreview.com"
    },
    {
      source: "MIT Technology Review",
      date: "May 29, 2026",
      title: "How the Pope's Magnifica Humanitas offers a template for individuals to meet the AI moment",
      description: "Despite a lack of regulation, we still have the ability to steer AI in ways that can benefit our common humanity — a thoughtful analysis.",
      url: "https://www.technologyreview.com/2026/05/29/1138107/how-the-popes-magnifica-humanitas-offers-a-template-for-individuals-to-meet-the-ai-moment/",
      sourceLabel: "techreview.com"
    },
    {
      source: "Anthropic",
      date: "May 28, 2026",
      title: "Introducing Claude Opus 4.8",
      description: "An upgrade to the Opus class of models, with stronger performance across coding, agentic tasks, and professional work, and the consistency to handle long-running work.",
      url: "https://www.anthropic.com/news/claude-opus-4-8",
      sourceLabel: "anthropic.com"
    },
    {
      source: "Anthropic",
      date: "Jun 10, 2026",
      title: "Policy on the AI Exponential",
      description: "AI is advancing at exponential speed, and the policymaking process was built for a slower world. Anthropic shares policy proposals to prepare institutions for AI progress.",
      url: "https://www.anthropic.com/policy-on-the-ai-exponential",
      sourceLabel: "anthropic.com"
    },
    {
      source: "Google Research",
      date: "Jun 2026",
      title: "Gemini for Science: AI experiments and tools for a new era of discovery",
      description: "A new collection of science tools and experiments to expand the scale and precision of scientific exploration, powered by Gemini.",
      url: "https://blog.google/innovation-and-ai/technology/research/gemini-for-science-io-2026/",
      sourceLabel: "blog.google"
    },
    {
      source: "Anthropic",
      date: "Jun 3, 2026",
      title: "What we learned mapping a year's worth of AI-enabled cyber threats",
      description: "Anthropic's analysis of AI-enabled cyber threats mapped to the MITRE ATT&CK framework — a year of observations and lessons learned.",
      url: "https://www.anthropic.com/news/AI-enabled-cyber-threats-mitre-attack",
      sourceLabel: "anthropic.com"
    },
    {
      source: "arXiv",
      date: "Continuous",
      title: "arXiv cs.AI — Latest AI Research Papers",
      description: "The latest academic submissions in Artificial Intelligence, updated daily. Over 1,100 recent papers covering agents, reasoning, MoE, TTS, and more.",
      url: "https://arxiv.org/list/cs.AI/recent",
      sourceLabel: "arxiv.org"
    }
  ],
  sources: [
    { label: "anthropic.com/news", url: "https://www.anthropic.com/news", desc: "Official Anthropic announcements" },
    { label: "blog.google — Google DeepMind", url: "https://blog.google/technology/google-deepmind/", desc: "Google AI research blog" },
    { label: "MIT Technology Review — AI", url: "https://www.technologyreview.com/topic/artificial-intelligence/", desc: "Independent tech journalism" },
    { label: "arxiv.org — cs.AI", url: "https://arxiv.org/list/cs.AI/recent", desc: "Peer-reviewed preprints" },
    { label: "deepseek.com", url: "https://www.deepseek.com", desc: "DeepSeek official" },
    { label: "openai.com/news", url: "https://openai.com/news/", desc: "OpenAI announcements" }
  ]
};